"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import LearningHeader from "@/components/learning/LearningHeader";
import ProgressBar from "@/components/learning/ProgressBar";
import type { LearningUnit, LessonProgress } from "@/types/learning";

type UnitWithCount=LearningUnit&{lessonCount:number;completedCount:number};
export default function LearnHomePage(){const supabase=useMemo(()=>createClient(),[]);const[units,setUnits]=useState<UnitWithCount[]>([]);const[loading,setLoading]=useState(true);
const load=useCallback(async()=>{const[{data:unitData},{data:lessonData},{data:{user}}]=await Promise.all([supabase.from("learning_units").select("*").eq("is_published",true).order("test_type").order("sort_order"),supabase.from("lessons").select("id,unit_id").eq("is_published",true),supabase.auth.getUser()]);let progress:LessonProgress[]=[];if(user){const{data}=await supabase.from("lesson_progress").select("lesson_id,status,progress_percent,best_quiz_score,last_block_order").eq("user_id",user.id);progress=(data??[])as LessonProgress[];}const mapped=((unitData??[])as LearningUnit[]).map(unit=>{const ids=(lessonData??[]).filter(l=>l.unit_id===unit.id).map(l=>l.id);return{...unit,lessonCount:ids.length,completedCount:ids.filter(id=>progress.some(p=>p.lesson_id===id&&p.status==="completed")).length};});setUnits(mapped);setLoading(false);},[supabase]);
useEffect(()=>{const id=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(id);},[load]);
if(loading)return <main className="grid min-h-screen place-items-center bg-slate-950 text-white">Cargando biblioteca...</main>;
const school=units.filter(u=>u.test_type==="SCHOOL");const paes=units.filter(u=>u.test_type==="M1");
const cards=(items:UnitWithCount[])=>items.map(unit=>{const pct=unit.lessonCount?Math.round(unit.completedCount/unit.lessonCount*100):0;return <Link key={unit.id} href={`/aprender/${unit.test_type.toLowerCase()}/${unit.slug}`} className="group rounded-3xl border border-white/10 bg-white/[0.05] p-7 transition hover:-translate-y-1 hover:border-teal-300"><div className="flex items-start justify-between gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-teal-300/10 text-xl font-black text-teal-300">{unit.icon}</span><span className="text-sm font-bold text-slate-500">{unit.lessonCount} lecciones</span></div><h2 className="mt-6 text-2xl font-black group-hover:text-teal-200">{unit.title}</h2><p className="mt-3 leading-7 text-slate-400">{unit.description}</p><div className="mt-6"><ProgressBar value={pct} label={`${unit.completedCount} completadas`}/></div></Link>});
return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white"><div className="mx-auto max-w-6xl"><LearningHeader title="Aprender" subtitle="MathLabs escolar y preparación PAES"/><section className="py-12"><p className="font-black text-teal-300">Biblioteca de aprendizaje</p><h1 className="mt-2 max-w-4xl text-4xl font-black sm:text-6xl">De tus bases escolares hasta la PAES</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-400">Clases profundas, ejemplos resueltos, práctica guiada y dominio por tema.</p><div className="mt-10 flex items-end justify-between gap-4"><div><p className="font-black text-sky-300">Matemática escolar</p><h2 className="mt-2 text-3xl font-black">5.º básico</h2></div><Link href="/matematica/5-basico" className="text-sm font-black text-teal-300">Ver mapa curricular →</Link></div><div className="mt-6 grid gap-5 md:grid-cols-2">{cards(school)}</div><div className="mt-14"><p className="font-black text-indigo-300">Preparación PAES</p><h2 className="mt-2 text-3xl font-black">Matemática M1</h2></div><div className="mt-6 grid gap-5 md:grid-cols-2">{cards(paes)}</div></section></div></main>;
}
