"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import MathLabsHeader from "@/components/mathlabs/MathLabsHeader";
import {createClient} from "@/lib/supabase/client";
import type {LearningSession} from "@/types/learning-os";
export default function SessionPage(){const supabase=useMemo(()=>createClient(),[]);const[s,setS]=useState<LearningSession|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");const[done,setDone]=useState("");
const load=useCallback(async()=>{const{data,error}=await supabase.rpc("get_my_active_learning_session");if(error)setMsg(error.message);setS((data??null) as LearningSession|null)},[supabase]);useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
async function start(m:number){setBusy(true);const{data,error}=await supabase.rpc("start_my_learning_session",{p_course_id:null,p_target_minutes:m});if(error)setMsg(error.message);else setS(data as LearningSession);setBusy(false)}
async function update(pos:number,status:"completed"|"skipped"){if(!s)return;setBusy(true);const{data,error}=await supabase.rpc("update_my_learning_session_item",{p_session_id:s.id,p_position:pos,p_status:status});if(error)setMsg(error.message);else setS(data as LearningSession);setBusy(false)}
async function finish(){if(!s)return;setBusy(true);const{data,error}=await supabase.rpc("complete_my_learning_session",{p_session_id:s.id});if(error)setMsg(error.message);else{const r=data as{activities_completed:number};setDone(`Sesión terminada: ${r.activities_completed} actividades completadas.`);setS(null)}setBusy(false)}
if(!s)return <main className="min-h-screen bg-slate-950 text-white"><MathLabsHeader/><section className="mx-auto max-w-5xl px-5 py-12"><div className="rounded-[2.75rem] border border-cyan-300/15 bg-white/[.03] p-8"><p className="font-black uppercase tracking-[.2em] text-cyan-200">Mi sesión de hoy</p><h1 className="mt-3 text-5xl font-black">¿Cuánto tiempo tienes?</h1><p className="mt-3 text-slate-400">Tu sesión queda guardada si sales y vuelves.</p><div className="mt-7 grid gap-3 sm:grid-cols-4">{[10,15,20,30].map(m=><button key={m} disabled={busy} type="button" onClick={()=>void start(m)} className="rounded-2xl border border-white/10 bg-slate-950/35 p-6"><p className="text-3xl font-black">{m}</p><p className="text-sm text-slate-500">minutos</p></button>)}</div>{done?<p className="mt-5 rounded-xl bg-emerald-300/10 p-4 text-emerald-100">🎉 {done}</p>:null}{msg?<p className="mt-5 rounded-xl bg-rose-300/10 p-4 text-rose-100">{msg}</p>:null}<Link href="/hoy" className="mt-5 inline-block text-sm font-black text-slate-500">← Mi centro</Link></div></section></main>;
const completed=s.items.filter(i=>i.status==="completed"||i.status==="skipped").length,p=Math.round(completed/Math.max(1,s.items.length)*100);
return <main className="min-h-screen bg-slate-950 text-white"><MathLabsHeader/><section className="mx-auto max-w-6xl px-5 py-10"><div className="rounded-[2rem] border border-white/10 bg-white/[.03] p-6"><div className="flex justify-between gap-5"><div><p className="font-black text-cyan-200">{s.course_name}</p><h1 className="mt-2 text-4xl font-black">Sesión de {s.target_minutes} min</h1></div><p className="text-3xl font-black text-cyan-200">{p}%</p></div><div className="mt-4 h-3 rounded-full bg-white/5"><div className="h-full rounded-full bg-cyan-300" style={{width:`${p}%`}}/></div></div><div className="mt-6 space-y-4">{s.items.map(i=><article key={i.position} className={`rounded-[1.75rem] border p-5 ${i.status==="current"?"border-cyan-300/30 bg-cyan-300/[.05]":"border-white/10 bg-white/[.02]"}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="text-3xl">{i.status==="completed"?"✓":i.emoji}</span><div><p className="text-xs font-black text-slate-500">Paso {i.position} · {i.estimated_minutes} min</p><h2 className="mt-1 text-xl font-black">{i.title}</h2><p className="mt-1 text-sm text-slate-500">{i.description}</p></div></div>{i.status==="current"?<div className="flex flex-wrap gap-2"><Link href={i.href} className="rounded-xl bg-cyan-300 px-4 py-3 text-sm font-black text-slate-950">Abrir →</Link><button disabled={busy} onClick={()=>void update(i.position,"completed")} className="rounded-xl border border-emerald-300/20 px-4 py-3 text-sm font-black text-emerald-200">Marcar lista</button><button disabled={busy} onClick={()=>void update(i.position,"skipped")} className="rounded-xl border border-white/10 px-4 py-3 text-sm font-black text-slate-500">Saltar</button></div>:<span className="text-sm font-black text-slate-600">{i.status}</span>}</div></article>)}</div>{s.status==="ready_to_complete"?<button disabled={busy} onClick={()=>void finish()} className="mt-6 w-full rounded-2xl bg-emerald-300 p-4 text-lg font-black text-slate-950">Terminar sesión ✓</button>:null}{msg?<p className="mt-5 rounded-xl bg-rose-300/10 p-4 text-rose-100">{msg}</p>:null}</section></main>}
