"use client";

import Link from "next/link";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import LearningHeader from "@/components/learning/LearningHeader";
import type { Lesson, LearningUnit } from "@/types/learning";

type Attempt={is_correct:boolean;questions:{axis:string}|{axis:string}[]|null};
type Recommendation=Lesson & {axis:string;unitSlug:string;accuracy:number|null;reason:string};

export default function StudyRoutePage(){const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const [recommendations,setRecommendations]=useState<Recommendation[]>([]);const [plan,setPlan]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [userId,setUserId]=useState<string|null>(null);
 
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return;}setUserId(user.id);const [{data:attemptData},{data:unitData},{data:lessonData},{data:progressData},{data:planData}]=await Promise.all([supabase.from('question_attempts').select('is_correct,questions(axis)').eq('user_id',user.id).order('created_at',{ascending:false}).limit(300),supabase.from('learning_units').select('*').eq('test_type','M1').eq('is_published',true),supabase.from('lessons').select('*').eq('is_published',true),supabase.from('lesson_progress').select('lesson_id,status').eq('user_id',user.id),supabase.from('study_plan_items').select('lesson_id').eq('user_id',user.id).in('status',['pending','in_progress'])]);const units=(unitData??[]) as LearningUnit[];const lessons=(lessonData??[]) as Lesson[];const completed=new Set((progressData??[]).filter(p=>p.status==='completed').map(p=>p.lesson_id));setPlan((planData??[]).map(p=>p.lesson_id));const map=new Map<string,{total:number;correct:number}>();for(const attempt of (attemptData??[]) as Attempt[]){const q=Array.isArray(attempt.questions)?attempt.questions[0]:attempt.questions;if(!q?.axis)continue;const current=map.get(q.axis)??{total:0,correct:0};current.total++;if(attempt.is_correct)current.correct++;map.set(q.axis,current);}const ranked=units.map(unit=>{const v=map.get(unit.axis);return {unit,accuracy:v?Math.round(v.correct/v.total*100):null,total:v?.total??0};}).sort((a,b)=>(a.accuracy??-1)-(b.accuracy??-1));const result:Recommendation[]=[];for(const entry of ranked){const candidates=lessons.filter(l=>l.unit_id===entry.unit.id&&!completed.has(l.id));for(const l of candidates.slice(0,2)){result.push({...l,axis:entry.unit.axis,unitSlug:entry.unit.slug,accuracy:entry.accuracy,reason:entry.accuracy===null?'Aún no hay suficientes respuestas en este eje.':`Tu precisión reciente en ${entry.unit.axis} es ${entry.accuracy}%.`});}if(result.length>=6)break;}setRecommendations(result.slice(0,6));setLoading(false);}

useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, []);

 async function addToPlan(item:Recommendation){if(!userId)return;await supabase.from('study_plan_items').upsert({user_id:userId,lesson_id:item.id,reason:item.reason,priority:item.accuracy===null?3:item.accuracy<40?5:item.accuracy<65?4:3,status:'pending'},{onConflict:'user_id,lesson_id'});setPlan(current=>[...new Set([...current,item.id])]);}
 if(loading)return <main className="grid min-h-screen place-items-center bg-slate-950 text-white">Construyendo tu ruta...</main>;
 return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white"><div className="mx-auto max-w-6xl"><LearningHeader title="Mi ruta de estudio" subtitle="Recomendaciones según tu desempeño" showRoute={false}/><section className="py-12"><p className="font-bold text-teal-300">Plan personalizado</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">Qué aprender a continuación</h1><p className="mt-4 max-w-3xl leading-7 text-slate-400">La ruta combina tus resultados de práctica con las lecciones que aún no completas. No reemplaza la revisión docente, pero convierte el diagnóstico en acciones concretas.</p><div className="mt-9 grid gap-5 md:grid-cols-2">{recommendations.map((item,index)=><article key={item.id} className="rounded-3xl border border-white/10 bg-white/[0.05] p-6"><div className="flex items-center justify-between gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-300/10 font-black text-indigo-200">{index+1}</span><span className="text-sm font-bold text-slate-500">{item.estimated_minutes} min</span></div><p className="mt-5 text-sm font-bold text-teal-300">{item.axis}</p><h2 className="mt-2 text-2xl font-black">{item.title}</h2><p className="mt-3 leading-7 text-slate-400">{item.reason}</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/aprender/leccion/${item.slug}`} className="rounded-xl bg-teal-300 px-4 py-3 font-black text-slate-950">Aprender ahora</Link><button disabled={plan.includes(item.id)} onClick={()=>void addToPlan(item)} className="rounded-xl border border-white/15 px-4 py-3 font-bold disabled:opacity-50">{plan.includes(item.id)?'En mi plan':'Agregar al plan'}</button></div></article>)}</div>{recommendations.length===0&&<div className="mt-8 rounded-2xl border border-white/10 bg-white/[0.04] p-7"><p className="text-slate-400">Ya completaste las lecciones recomendadas. Continúa con práctica adaptativa para generar un nuevo diagnóstico.</p><Link href="/adaptativo" className="mt-5 inline-block rounded-xl bg-teal-300 px-5 py-3 font-black text-slate-950">Entrenamiento adaptativo</Link></div>}</section></div></main>}
