"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import MathLabsHeader from "@/components/mathlabs/MathLabsHeader";
import {createClient} from "@/lib/supabase/client";
type Course={id:string;slug:string;name:string;description:string};
export default function StartPage(){const router=useRouter(),supabase=useMemo(()=>createClient(),[]);const[courses,setCourses]=useState<Course[]>([]);const[courseId,setCourseId]=useState("");const[minutes,setMinutes]=useState(20);const[focus,setFocus]=useState("balanced");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
useEffect(()=>{let cancelled=false;async function load(){const{data:a}=await supabase.auth.getUser();if(!a.user){router.replace("/login");return}const{data,error}=await supabase.from("courses").select("id,slug,name,description").eq("is_available",true).eq("is_published",true).order("sort_order");if(!cancelled){setCourses((data??[]) as Course[]);if((data??[]).length)setCourseId(String(data![0].id));setMessage(error?.message??"")}}void load();return()=>{cancelled=true}},[router,supabase]);
async function save(){if(!courseId)return;setBusy(true);const{error}=await supabase.rpc("configure_my_learning_profile",{p_course_id:courseId,p_preferred_session_minutes:minutes,p_focus_mode:focus});if(error){setMessage(error.message);setBusy(false);return}router.push("/hoy")}
return <main className="min-h-screen bg-slate-950 text-white"><MathLabsHeader/><section className="mx-auto max-w-5xl px-5 py-12"><div className="rounded-[2.75rem] border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,.18),transparent_35%),#0f172a] p-8"><p className="text-sm font-black uppercase tracking-[.2em] text-cyan-200">Configura MathLabs</p><h1 className="mt-3 text-5xl font-black">Construyamos tu ruta.</h1><p className="mt-4 text-lg leading-8 text-slate-300">Elige tu curso, tiempo de estudio y enfoque.</p></div>
<div className="mt-7 rounded-[2rem] border border-white/10 bg-white/[.03] p-6"><p className="font-black text-cyan-200">1 · Curso</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{courses.map(c=><button key={c.id} type="button" onClick={()=>setCourseId(c.id)} className={`rounded-2xl border p-5 text-left ${courseId===c.id?"border-cyan-300 bg-cyan-300/[.07]":"border-white/10 bg-slate-950/35"}`}><p className="text-2xl font-black">{c.name}</p><p className="mt-2 text-sm text-slate-500">{c.description}</p></button>)}</div>
<p className="mt-7 font-black text-fuchsia-200">2 · Sesión ideal</p><div className="mt-3 flex flex-wrap gap-2">{[10,15,20,30].map(v=><button key={v} type="button" onClick={()=>setMinutes(v)} className={`rounded-xl px-4 py-3 font-black ${minutes===v?"bg-fuchsia-300 text-slate-950":"border border-white/10"}`}>{v} min</button>)}</div>
<p className="mt-7 font-black text-amber-200">3 · Enfoque</p><div className="mt-3 grid gap-3 md:grid-cols-3">{[["balanced","⚖️ Equilibrado"],["reinforcement","🧩 Reforzar"],["challenge","🚀 Desafíos"]].map(([v,l])=><button key={v} type="button" onClick={()=>setFocus(v)} className={`rounded-xl border p-4 font-black ${focus===v?"border-amber-300 bg-amber-300/[.07]":"border-white/10"}`}>{l}</button>)}</div>{message?<p className="mt-5 rounded-xl bg-rose-300/10 p-4 text-rose-100">{message}</p>:null}<button disabled={busy||!courseId} type="button" onClick={()=>void save()} className="mt-7 w-full rounded-2xl bg-cyan-300 p-4 text-lg font-black text-slate-950 disabled:opacity-50">{busy?"Guardando...":"Entrar a mi centro →"}</button></div></section></main>}
