"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { LearningUnit, Lesson, LessonBlock } from "@/types/learning";

const blockTypes=['objective','text','concepts','formula','visual','examples','common_errors','tip','summary','video','practice'];
const emptyUnit:LearningUnit={id:'',test_type:'M1',axis:'Números',slug:'',title:'',description:'',icon:'π',sort_order:1,is_published:false};
const emptyLesson:Lesson={id:'',unit_id:'',slug:'',title:'',summary:'',objective:'',estimated_minutes:15,difficulty:'Básico',sort_order:1,is_published:false,video_url:null,thumbnail_url:null,prerequisites:[],tags:[],question_filter:{keywords:[]}};

type EditableBlock=Omit<LessonBlock,'id'> & {id?:string;dataText:string};

export default function ContentAdminPage(){const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const [units,setUnits]=useState<LearningUnit[]>([]);const [lessons,setLessons]=useState<Lesson[]>([]);const [unitForm,setUnitForm]=useState<LearningUnit>(emptyUnit);const [lessonForm,setLessonForm]=useState<Lesson>(emptyLesson);const [blocks,setBlocks]=useState<EditableBlock[]>([]);const [search,setSearch]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 useEffect(()=>{void initialize();},[]);
 async function initialize(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return;}const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin'){router.replace('/dashboard');return;}await load();setLoading(false);}
 async function load(){const [{data:u},{data:l}]=await Promise.all([supabase.from('learning_units').select('*').order('test_type').order('sort_order'),supabase.from('lessons').select('*').order('unit_id').order('sort_order')]);setUnits((u??[]) as LearningUnit[]);setLessons((l??[]) as Lesson[]);}
 async function saveUnit(){setSaving(true);const payload={...unitForm,id:unitForm.id.trim(),slug:unitForm.slug.trim()};const {error}=await supabase.from('learning_units').upsert(payload);setMessage(error?error.message:'Unidad guardada.');if(!error){setUnitForm(emptyUnit);await load();}setSaving(false);}
 async function editLesson(lesson:Lesson){setLessonForm(lesson);const {data}=await supabase.from('lesson_blocks').select('*').eq('lesson_id',lesson.id).order('sort_order');setBlocks(((data??[]) as LessonBlock[]).map(b=>({...b,dataText:JSON.stringify(b.data,null,2)})));window.scrollTo({top:0,behavior:'smooth'});}
 function addBlock(){setBlocks(current=>[...current,{lesson_id:lessonForm.id,block_type:'text',title:'Nuevo bloque',content:'',data:{},sort_order:current.length+1,dataText:'{}'}]);}
 function moveBlock(index:number,direction:-1|1){const next=[...blocks];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setBlocks(next.map((b,i)=>({...b,sort_order:i+1})));}
 async function saveLesson(){setSaving(true);setMessage('');try{if(!lessonForm.id||!lessonForm.unit_id||!lessonForm.slug||!lessonForm.title)throw new Error('Completa ID, unidad, slug y título.');const payload={...lessonForm,tags:lessonForm.tags,prerequisites:lessonForm.prerequisites};const {error}=await supabase.from('lessons').upsert(payload);if(error)throw error;await supabase.from('lesson_blocks').delete().eq('lesson_id',lessonForm.id);const parsed=blocks.map((b,i)=>({lesson_id:lessonForm.id,block_type:b.block_type,title:b.title,content:b.content,data:JSON.parse(b.dataText||'{}'),sort_order:i+1}));if(parsed.length){const {error:blockError}=await supabase.from('lesson_blocks').insert(parsed);if(blockError)throw blockError;}setMessage('Lección y bloques guardados.');await load();}catch(error){setMessage(error instanceof Error?error.message:'No fue posible guardar.');}setSaving(false);}
 function newLesson(){setLessonForm({...emptyLesson,unit_id:units[0]?.id??''});setBlocks([]);}
 if(loading)return <main className="grid min-h-screen place-items-center bg-slate-950 text-white">Cargando editor...</main>;
 const filtered=lessons.filter(l=>`${l.title} ${l.slug} ${l.id}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white"><div className="mx-auto max-w-[1500px]"><header className="flex flex-col gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-black">PAESLab Contenidos</h1><p className="mt-2 text-slate-400">Unidades, lecciones y bloques de aprendizaje</p></div><div className="flex gap-3"><a href="/admin" className="rounded-xl border border-white/15 px-4 py-2 font-bold">Preguntas</a><a href="/aprender" className="rounded-xl bg-teal-300 px-4 py-2 font-black text-slate-950">Ver plataforma</a></div></header>{message&&<p className="mt-6 rounded-xl border border-indigo-300/20 bg-indigo-300/10 p-4 text-indigo-100">{message}</p>}
 <section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h2 className="text-xl font-black">Crear o actualizar unidad</h2><div className="mt-5 grid gap-3 md:grid-cols-4"><input placeholder="ID" value={unitForm.id} onChange={e=>setUnitForm({...unitForm,id:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3"/><input placeholder="Slug" value={unitForm.slug} onChange={e=>setUnitForm({...unitForm,slug:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3"/><input placeholder="Título" value={unitForm.title} onChange={e=>setUnitForm({...unitForm,title:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3"/><input placeholder="Eje" value={unitForm.axis} onChange={e=>setUnitForm({...unitForm,axis:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3"/></div><textarea placeholder="Descripción" value={unitForm.description} onChange={e=>setUnitForm({...unitForm,description:e.target.value})} className="mt-3 w-full rounded-xl bg-slate-900 px-4 py-3"/><div className="mt-4 flex items-center gap-4"><label className="flex items-center gap-2"><input type="checkbox" checked={unitForm.is_published} onChange={e=>setUnitForm({...unitForm,is_published:e.target.checked})}/> Publicada</label><button disabled={saving} onClick={()=>void saveUnit()} className="rounded-xl bg-indigo-300 px-5 py-3 font-black text-slate-950">Guardar unidad</button></div></section>
 <section className="mt-8 grid gap-8 xl:grid-cols-[0.9fr_1.1fr]"><article className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Editor de lección</h2><button onClick={newLesson} className="rounded-xl border border-white/15 px-4 py-2 font-bold">Nueva</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><input placeholder="ID" value={lessonForm.id} onChange={e=>setLessonForm({...lessonForm,id:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3"/><select value={lessonForm.unit_id} onChange={e=>setLessonForm({...lessonForm,unit_id:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3">{units.map(u=><option key={u.id} value={u.id}>{u.test_type} · {u.title}</option>)}</select><input placeholder="Slug" value={lessonForm.slug} onChange={e=>setLessonForm({...lessonForm,slug:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3"/><input placeholder="Título" value={lessonForm.title} onChange={e=>setLessonForm({...lessonForm,title:e.target.value})} className="rounded-xl bg-slate-900 px-4 py-3"/></div><textarea placeholder="Resumen" value={lessonForm.summary} onChange={e=>setLessonForm({...lessonForm,summary:e.target.value})} className="mt-3 w-full rounded-xl bg-slate-900 px-4 py-3"/><textarea placeholder="Objetivo" value={lessonForm.objective} onChange={e=>setLessonForm({...lessonForm,objective:e.target.value})} className="mt-3 w-full rounded-xl bg-slate-900 px-4 py-3"/><div className="mt-3 grid gap-3 sm:grid-cols-3"><input type="number" value={lessonForm.estimated_minutes} onChange={e=>setLessonForm({...lessonForm,estimated_minutes:Number(e.target.value)})} className="rounded-xl bg-slate-900 px-4 py-3"/><select value={lessonForm.difficulty} onChange={e=>setLessonForm({...lessonForm,difficulty:e.target.value as Lesson['difficulty']})} className="rounded-xl bg-slate-900 px-4 py-3"><option>Básico</option><option>Medio</option><option>Avanzado</option></select><input type="number" value={lessonForm.sort_order} onChange={e=>setLessonForm({...lessonForm,sort_order:Number(e.target.value)})} className="rounded-xl bg-slate-900 px-4 py-3"/></div><label className="mt-4 flex items-center gap-2"><input type="checkbox" checked={lessonForm.is_published} onChange={e=>setLessonForm({...lessonForm,is_published:e.target.checked})}/> Publicada</label>
 <div className="mt-7 flex items-center justify-between"><h3 className="text-xl font-black">Bloques</h3><button onClick={addBlock} className="rounded-xl bg-teal-300 px-4 py-2 font-black text-slate-950">+ Bloque</button></div><div className="mt-4 space-y-4">{blocks.map((block,index)=><div key={index} className="rounded-2xl border border-white/10 bg-slate-900/60 p-4"><div className="flex flex-wrap gap-2"><select value={block.block_type} onChange={e=>setBlocks(blocks.map((b,i)=>i===index?{...b,block_type:e.target.value}:b))} className="rounded-lg bg-slate-950 px-3 py-2">{blockTypes.map(t=><option key={t}>{t}</option>)}</select><input value={block.title} onChange={e=>setBlocks(blocks.map((b,i)=>i===index?{...b,title:e.target.value}:b))} className="flex-1 rounded-lg bg-slate-950 px-3 py-2"/><button onClick={()=>moveBlock(index,-1)}>↑</button><button onClick={()=>moveBlock(index,1)}>↓</button><button onClick={()=>setBlocks(blocks.filter((_,i)=>i!==index))} className="text-rose-300">Eliminar</button></div><textarea value={block.content} onChange={e=>setBlocks(blocks.map((b,i)=>i===index?{...b,content:e.target.value}:b))} placeholder="Contenido" className="mt-3 w-full rounded-lg bg-slate-950 px-3 py-2"/><textarea rows={7} value={block.dataText} onChange={e=>setBlocks(blocks.map((b,i)=>i===index?{...b,dataText:e.target.value}:b))} placeholder="Datos JSON" className="mt-3 w-full rounded-lg bg-slate-950 px-3 py-2 font-mono text-sm"/></div>)}</div><button disabled={saving} onClick={()=>void saveLesson()} className="mt-6 w-full rounded-xl bg-teal-300 px-5 py-4 font-black text-slate-950">{saving?'Guardando...':'Guardar lección completa'}</button></article>
 <article className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lección..." className="w-full rounded-xl bg-slate-900 px-4 py-3"/><div className="mt-5 max-h-[1400px] space-y-3 overflow-y-auto">{filtered.map(l=><button key={l.id} onClick={()=>void editLesson(l)} className="w-full rounded-2xl border border-white/10 bg-slate-900/60 p-5 text-left hover:border-teal-300"><div className="flex justify-between gap-4"><div><p className="text-sm font-bold text-teal-300">{units.find(u=>u.id===l.unit_id)?.title}</p><h3 className="mt-2 text-xl font-black">{l.title}</h3><p className="mt-2 text-sm text-slate-400">{l.summary}</p></div><span className={l.is_published?'text-emerald-300':'text-amber-300'}>{l.is_published?'Publicada':'Borrador'}</span></div></button>)}</div></article></section>
 </div></main>}
