"use client";
import {useMemo,useState} from "react";
import type {SixthGradeLabDefinition} from "@/data/sixth-grade-labs";

function Box({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/10 bg-slate-950/45 p-4 text-center"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p></div>}

function Factors(){const[n,setN]=useState(36);const f=useMemo(()=>Array.from({length:n},(_,i)=>i+1).filter(x=>n%x===0),[n]);return <div className="space-y-5"><label className="block rounded-2xl border border-white/10 bg-slate-950/45 p-4">Número: {n}<input className="mt-3 w-full accent-cyan-300" type="range" min="2" max="80" value={n} onChange={e=>setN(Number(e.target.value))}/></label><div className="flex flex-wrap justify-center gap-2">{f.map(x=><span key={x} className="rounded-xl bg-cyan-300/10 px-3 py-2 font-black text-cyan-100">{x}</span>)}</div><div className="grid gap-3 sm:grid-cols-2"><Box label="Factores" value={f.length}/><Box label="Tipo" value={f.length===2?"Primo":"Compuesto"}/></div></div>}
function Ratio(){const[a,setA]=useState(3);const[b,setB]=useState(5);const gcd=(x:number,y:number):number=>y===0?x:gcd(y,x%y);const g=gcd(a,b);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Azul: {a}<input className="mt-3 w-full accent-cyan-300" type="range" min="1" max="12" value={a} onChange={e=>setA(Number(e.target.value))}/></label><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Amarillo: {b}<input className="mt-3 w-full accent-amber-300" type="range" min="1" max="12" value={b} onChange={e=>setB(Number(e.target.value))}/></label></div><p className="text-center text-4xl font-black">{a}:{b} <span className="text-slate-600">=</span> <span className="text-cyan-200">{a/g}:{b/g}</span></p></div>}
function Percent(){const[p,setP]=useState(25);return <div className="space-y-5"><label className="block rounded-2xl border border-white/10 bg-slate-950/45 p-4">{p}%<input className="mt-3 w-full accent-emerald-300" type="range" min="0" max="100" value={p} onChange={e=>setP(Number(e.target.value))}/></label><div className="mx-auto grid max-w-sm grid-cols-10 overflow-hidden rounded-2xl border border-white/10">{Array.from({length:100},(_,i)=><span key={i} className={`aspect-square border-b border-r border-slate-950/30 ${i<p?"bg-emerald-300":"bg-slate-800"}`}/>)}</div><div className="grid gap-3 sm:grid-cols-3"><Box label="%" value={`${p}%`}/><Box label="Fracción" value={`${p}/100`}/><Box label="Decimal" value={(p/100).toFixed(2).replace(".",",")}/></div></div>}
function Mixed(){const[w,setW]=useState(1);const[n,setN]=useState(3);const[d,setD]=useState(4);const sn=Math.min(n,d-1);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Enteros: {w}<input className="mt-3 w-full accent-rose-300" type="range" min="0" max="4" value={w} onChange={e=>setW(Number(e.target.value))}/></label><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Numerador: {sn}<input className="mt-3 w-full accent-rose-300" type="range" min="1" max={Math.max(1,d-1)} value={sn} onChange={e=>setN(Number(e.target.value))}/></label><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Denominador: {d}<input className="mt-3 w-full accent-rose-300" type="range" min="2" max="10" value={d} onChange={e=>{const next=Number(e.target.value);setD(next);setN(v=>Math.min(v,next-1))}}/></label></div><p className="text-center text-4xl font-black">{w} {sn}/{d} <span className="text-slate-600">=</span> <span className="text-rose-200">{w*d+sn}/{d}</span></p></div>}
function Decimal(){const[v,setV]=useState(2.35);const[f,setF]=useState(10);return <div className="space-y-5"><label className="block rounded-2xl border border-white/10 bg-slate-950/45 p-4">Número: {v.toFixed(2).replace(".",",")}<input className="mt-3 w-full accent-sky-300" type="range" min="0.1" max="9.9" step="0.05" value={v} onChange={e=>setV(Number(e.target.value))}/></label><div className="flex justify-center gap-2">{[10,100,1000].map(x=><button key={x} type="button" onClick={()=>setF(x)} className={`rounded-xl px-4 py-2 font-black ${f===x?"bg-sky-300 text-slate-950":"border border-white/10"}`}>× {x}</button>)}</div><p className="text-center text-4xl font-black">{v.toFixed(2).replace(".",",")} × {f} = <span className="text-sky-200">{Number((v*f).toFixed(4)).toLocaleString("es-CL")}</span></p></div>}
function Equation(){const[x,setX]=useState(7);const[a,setA]=useState(5);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">x: {x}<input className="mt-3 w-full accent-violet-300" type="range" min="1" max="20" value={x} onChange={e=>setX(Number(e.target.value))}/></label><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Suma: {a}<input className="mt-3 w-full accent-violet-300" type="range" min="1" max="12" value={a} onChange={e=>setA(Number(e.target.value))}/></label></div><div className="grid gap-3 md:grid-cols-[1fr_auto_1fr] md:items-center"><Box label="Lado izquierdo" value={`x + ${a}`}/><span className="text-center text-4xl font-black text-amber-200">=</span><Box label="Lado derecho" value={x+a}/></div><p className="text-center text-slate-400">Quita {a} a ambos lados y queda <strong className="text-violet-200">x = {x}</strong>.</p></div>}
function Angle(){const[d,setD]=useState(70);const r=d*Math.PI/180;const x=50+38*Math.cos(r),y=50-38*Math.sin(r);const type=d<90?"Agudo":d===90?"Recto":d<180?"Obtuso":"Extendido";return <div className="space-y-5"><label className="block rounded-2xl border border-white/10 bg-slate-950/45 p-4">Ángulo: {d}°<input className="mt-3 w-full accent-amber-300" type="range" min="10" max="180" value={d} onChange={e=>setD(Number(e.target.value))}/></label><svg viewBox="0 0 100 100" className="mx-auto max-w-md rounded-2xl border border-white/10 bg-slate-950/45"><line x1="50" y1="50" x2="92" y2="50" stroke="#fbbf24" strokeWidth="2.5"/><line x1="50" y1="50" x2={x} y2={y} stroke="#22d3ee" strokeWidth="2.5"/></svg><p className="text-center text-3xl font-black">{d}° · <span className="text-amber-200">{type}</span></p></div>}
function Volume(){const[l,setL]=useState(4);const[w,setW]=useState(3);const[h,setH]=useState(2);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[["Largo",l,setL],["Ancho",w,setW],["Alto",h,setH]].map(([label,value,setter])=><label key={String(label)} className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">{String(label)}: {Number(value)}<input className="mt-3 w-full accent-cyan-300" type="range" min="1" max="8" value={Number(value)} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/></label>)}</div><p className="text-center text-4xl font-black">{l} × {w} × {h} = <span className="text-cyan-200">{l*w*h} unidades³</span></p></div>}
function Probability(){const[t,setT]=useState(40);const[h,setH]=useState(0);function run(){let heads=0;for(let i=0;i<t;i+=1)if(Math.random()<.5)heads+=1;setH(heads)}return <div className="space-y-5"><label className="block rounded-2xl border border-white/10 bg-slate-950/45 p-4">Lanzamientos: {t}<input className="mt-3 w-full accent-emerald-300" type="range" min="10" max="300" step="10" value={t} onChange={e=>setT(Number(e.target.value))}/></label><button type="button" onClick={run} className="w-full rounded-2xl bg-emerald-300 p-4 font-black text-slate-950">🪙 Simular</button><div className="grid gap-3 sm:grid-cols-3"><Box label="Caras" value={h}/><Box label="Sellos" value={t-h}/><Box label="% caras" value={`${Math.round(h*100/t)}%`}/></div></div>}
function DoubleBar(){const[a,setA]=useState(6);const[b,setB]=useState(9);const max=Math.max(a,b);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Grupo 1: {a}<input className="mt-3 w-full accent-cyan-300" type="range" min="1" max="12" value={a} onChange={e=>setA(Number(e.target.value))}/></label><label className="rounded-2xl border border-white/10 bg-slate-950/45 p-4">Grupo 2: {b}<input className="mt-3 w-full accent-fuchsia-300" type="range" min="1" max="12" value={b} onChange={e=>setB(Number(e.target.value))}/></label></div><div className="mx-auto flex h-64 max-w-md items-end justify-center gap-8 rounded-2xl border border-white/10 bg-slate-950/45 p-6"><div className="w-24 rounded-t-xl bg-cyan-300 text-center font-black text-slate-950" style={{height:`${a/max*90}%`}}>{a}</div><div className="w-24 rounded-t-xl bg-fuchsia-300 text-center font-black text-slate-950" style={{height:`${b/max*90}%`}}>{b}</div></div></div>}

export default function SixthGradeLabPlayground({lab}:{lab:SixthGradeLabDefinition}){if(lab.type==="factors")return <Factors/>;if(lab.type==="ratio")return <Ratio/>;if(lab.type==="percent")return <Percent/>;if(lab.type==="mixed_fraction")return <Mixed/>;if(lab.type==="decimal_scale")return <Decimal/>;if(lab.type==="equation")return <Equation/>;if(lab.type==="angle")return <Angle/>;if(lab.type==="volume")return <Volume/>;if(lab.type==="probability")return <Probability/>;return <DoubleBar/>}
