"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import MathLabsHeader from "@/components/mathlabs/MathLabsHeader";
import {createClient} from "@/lib/supabase/client";
type Axis={id:string;name:string;icon:string}; type Topic={id:string;axis_id:string;slug:string;title:string;summary:string;sort_order:number}; type Unit={id:string;slug:string;title:string;description:string;icon:string;sort_order:number};
export default function Course6(){const supabase=useMemo(()=>createClient(),[]);const[axes,setAxes]=useState<Axis[]>([]),[topics,setTopics]=useState<Topic[]>([]),[units,setUnits]=useState<Unit[]>([]);const[active,setActive]=useState(false),[msg,setMsg]=useState("");
const load=useCallback(async()=>{const{data:a}=await supabase.auth.getUser();const[ax,tp,un]=await Promise.all([supabase.from("curriculum_axes").select("id,name,icon").eq("course_id","cl-6-basico").eq("is_published",true).order("sort_order"),supabase.from("knowledge_topics").select("id,axis_id,slug,title,summary,sort_order").eq("course_id","cl-6-basico").eq("is_published",true).order("sort_order"),supabase.from("learning_units").select("id,slug,title,description,icon,sort_order").like("slug","6-basico-%").eq("is_published",true).order("sort_order")]);setAxes((ax.data??[]) as Axis[]);setTopics((tp.data??[]) as Topic[]);setUnits((un.data??[]) as Unit[]);setMsg(ax.error?.message??tp.error?.message??un.error?.message??"");if(a.user){const{data:e}=await supabase.from("student_course_enrollments").select("status").eq("user_id",a.user.id).eq("course_id","cl-6-basico").maybeSingle();setActive(e?.status==="active")}},[supabase]);useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
async function activate(){const{error}=await supabase.rpc("configure_my_learning_profile",{p_course_id:"cl-6-basico",p_preferred_session_minutes:20,p_focus_mode:"balanced"});if(error)setMsg(error.message);else setActive(true)}
return <main className="min-h-screen bg-slate-950 text-white"><MathLabsHeader/><section className="mx-auto max-w-7xl px-5 py-12"><div className="rounded-[2.75rem] border border-white/10 bg-[radial-gradient(circle_at_top_left,rgba(168,85,247,.16),transparent_30%),radial-gradient(circle_at_bottom_right,rgba(34,211,238,.15),transparent_30%),#0f172a] p-8"><p className="font-black uppercase tracking-[.2em] text-fuchsia-200">MathLabs escolar</p><h1 className="mt-2 text-6xl font-black">6° básico</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">36 temas, seis unidades, diagnóstico, práctica segura, repasos y diez laboratorios.</p><div className="mt-6 flex flex-wrap gap-3">{active?<Link href="/hoy" className="rounded-2xl bg-cyan-300 px-5 py-3 font-black text-slate-950">Ir a Mi centro →</Link>:<button onClick={()=>void activate()} className="rounded-2xl bg-fuchsia-300 px-5 py-3 font-black text-slate-950">Usar 6° como mi curso</button>}<Link href="/sesion" className="rounded-2xl border border-white/10 px-5 py-3 font-black">Mi sesión de hoy</Link><Link href="/laboratorio/6-basico" className="rounded-2xl border border-white/10 px-5 py-3 font-black">🧪 Laboratorios</Link></div></div>{msg?<p className="mt-5 rounded-xl bg-rose-300/10 p-4 text-rose-100">{msg}</p>:null}
<section className="mt-8"><p className="font-black text-cyan-200">Unidades</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{units.map(u=><Link key={u.id} href={`/aprender/school/${u.slug}`} className="rounded-[2rem] border border-white/10 bg-white/[.03] p-6"><p className="text-4xl">{u.icon}</p><h2 className="mt-4 text-xl font-black">{u.title}</h2><p className="mt-2 text-sm text-slate-500">{u.description}</p><p className="mt-4 font-black text-cyan-200">Abrir unidad →</p></Link>)}</div></section>
<section className="mt-10"><h2 className="text-3xl font-black">Mapa curricular</h2><div className="mt-5 space-y-5">{axes.map(a=><article key={a.id} className="rounded-[2rem] border border-white/10 bg-white/[.02] p-6"><h3 className="text-xl font-black">{a.icon} {a.name}</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{topics.filter(t=>t.axis_id===a.id).map(t=><Link key={t.id} href={`/matematica/tema/${t.slug}`} className="rounded-2xl border border-white/10 bg-slate-950/35 p-4"><p className="font-black">{t.title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{t.summary}</p></Link>)}</div></article>)}</div></section></section></main>}
